-- Run this in the Supabase SQL Editor.

create table if not exists public.thermal_results (
    id bigint generated by default as identity primary key,
    timestamp timestamptz null,
    image_name text null,
    capture_date text null,
    capture_time text null,
    section text null,
    ohe_mast text null,
    scale_max real null,
    scale_min real null,
    wire_max real null,
    wire_min real null,
    delta_t real null,
    status text null,
    attend_in text null
);

alter table public.thermal_results
enable row level security;

-- This project uses SUPABASE_SECRET_KEY on the server.
-- Therefore you do NOT need a public/anon INSERT policy.
-- Never put the secret key in browser-side JavaScript or GitHub.
